# Generated by Django 5.2.15 on 2026-07-14 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('VALID', 'Valid'), ('EXPIRING', 'Expiring Soon'), ('ACTION_REQUIRED', 'Action Required')], default='VALID', max_length=20),
        ),
    ]
