# Generated by Django 5.2.15 on 2026-07-18 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_document_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='status',
        ),
    ]
